name: 'fraud_detection'
version: '1.0.0'
config-version: 2

profile: 'fraud_detection'

model-paths: ["models"]

models:
  fraud_detection:
    staging:
      +materialized: view
      +schema: fraud_staging_dev
    marts:
      +materialized: table
      +schema: fraud_marts_dev
      +tags: ['daily']
